### ISSUE TITLE
use Flask instead of FastAPI

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/wp4ds#40]
My first attempt to build this tutorial used [Flask](https://flask.palletsprojects.com/) as a server rather than [FastAPI](https://fastapi.tiangolo.com/). While working on the authentication lesson, I'm wondering if I should have stayed with Flask. For example, managing redirect-on-login in FastAPI is more complex than doing it in Flask, and while FastAPI is better for serving JSON for REST APIs, this tutorial is mostly serving HTML.

**Comment by juananpe** [comment]
For a tutorial aimed at data scientists that prioritizes simplicity, I would recommend using **Flask**.  It has good documentation and a large community, making it beginner-friendly and ideal for newcomers to web development.
Anyway, I have more experience with Flask than with FastAPI so I might be biased.

**Comment by gvwilson** [comment]
I agree - I've started work in https://github.com/gvwilson/wp4ds/tree/flask-not-fastapi and will have a PR for you to review by Monday if you have time. Once that's in I'll resume work on authentication... thank you.

**Comment by juananpe** [comment]
Thank you for the update, Greg. I'll be happy to review your PR when it's ready. Looking forward to it.
