### ISSUE TITLE
Add a section on i18n/L10n

### ISSUE THREAD

**Issue by juananpe** [gvwilson/wp4ds#44]
Some topics to cover in this section could include:

* Translating text and formatting
* Handling date, time, and number formats
* Character encoding and Unicode
* Using libraries and frameworks for i18n and l10n (e.g., gettext, [FormatJS](https://formatjs.io/))

**Comment by juananpe** [comment]
What do you think, @gvwilson?

**Comment by gvwilson** [comment]
I think this is a great idea and I would really like to include it.
